version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONF_RADARR}:/config
      - ${MOVIES_RADARR_PATH}:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - my-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONF_SONARR}:/config
      - ${MOVIES_SONARR_PATH}:/movies
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - my-network

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONF_BAZARR}:/config
      - ${VIDEO_PATH}:/movies #optional
      - ${MEDIA_PATH}:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - my-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONF_PROWLARR}:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    external: true